version: '2'
services:
  api:
    image: jivecakeapi
    ports:
      - "8080:8080"
    links:
      - mongo
    volumes:
      - ..:/root/jivecakeapi
      - ./luis.yml:/root/settings.yml
      - ./gcp-credentials.json:/root/gcp-credentials.json
  mongo:
    image: mongo:3.4.1