version: '2'
services:
  api:
    image: jivecakeapi
    ports:
      - "8080:8080"
    links:
      - mongo
    volumes:
      - ..:/root/jivecakeapi
      - ./settings:/root/settings.yml
  mongo:
    image: mongo:3.4.1