rootOAuthIds:
  - ""
errorRecipients:
  - ""

facebook:
  messengerWebhookVerifyToken: "default"
  secret: "default"
  accessToken: "default"

oauth:
  nonInteractiveClientId: "default"
  nonInteractiveSecret: "default"
  domain: "default"
  audience: http://127.0.0.1:8080/

paypal:
  webhookId: "default"
  clientId: "default"
  clientSecret: "default"
  mode: production

sentry:
  dsn: https://1:1@sentry.io/1
  environment: travis

mandrill:
  mock: true
  key: "default"

stripe:
  secretKey: "default"
  publishableKey: "default"
  signingSecret: "default"

gcp:
  bucket: "default"

stripe:
  secretKey: "default"
  publishableKey: "default"

databases:
  - 127.0.0.1:27017

corsOrigins:
  - https://jivecake.com
  - http://jivecake.com

server:
  gzip:
    enabled: false
  applicationConnectors:
    - type: http
      port: 8080

logging:
  level: INFO
  loggers:
    "io.dropwizard": ALL

  appenders:
    - type: console
    - type: file
      threshold: DEBUG
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/application.log
      maxFileSize: 100MB
      archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC